title:              Manikanth Reddy
email:              manikanth.iitkgp@gmail.com
description:        Manikanth Reddy's Website
author:             Manikanth Reddy
baseurl:            ""
url:                "https://manikanthr5.github.io"

# Social Profiles
twitter_username:   manikanthr5
github_username:    manikanthr5
facebook_username:  
instagram_username:  
linkedin_username: manikanthr5

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-112739439-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
